# Generated by Django 5.2.11 on 2026-03-05 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodbanks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBankAdmin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='foodbanks.foodbank')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
