server {
    listen 80;
    server_name _;

    resolver 127.0.0.11 valid=10s ipv6=off;

    gzip on;
    gzip_vary on;
    gzip_comp_level 6;
    gzip_min_length 256;
    gzip_types
        application/javascript
        application/json
        application/xml
        image/svg+xml
        text/css
        text/plain
        text/xml;

    location ~* \.(js|css|woff2?|ttf|otf|eot|ico|png|jpg|jpeg|gif|webp|svg)$ {
        set $frontend_upstream http://frontend:5173;
        proxy_pass $frontend_upstream;
        proxy_set_header Host $host;
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location /api/ {
        set $django_upstream http://django:8000;
        proxy_pass         $django_upstream;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60s;
        proxy_send_timeout    60s;
        proxy_read_timeout    60s;
    }

    location /static/ {
        alias /vol/static/;
    }

    location / {
        set $frontend_upstream http://frontend:5173;
        proxy_pass $frontend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
