# Generated by Django 5.2.11 on 2026-03-05 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbanks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.TextField()),
                ('category', models.CharField(choices=[('tinned_goods', 'Tinned Goods'), ('dried_goods', 'Dried Goods'), ('fresh', 'Fresh'), ('dairy', 'Dairy'), ('baby', 'Baby'), ('hygiene', 'Hygiene')], max_length=20)),
                ('urgency', models.CharField(choices=[('urgent', 'Urgent'), ('needed', 'Needed'), ('optional', 'Optional')], max_length=10)),
                ('quantity_needed', models.PositiveIntegerField(default=0)),
                ('unit', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('food_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list_items', to='foodbanks.foodbank')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
