# Generated by Django 5.2.11 on 2026-03-05 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbanks', '0002_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipe_name', models.TextField()),
                ('description', models.TextField()),
                ('serves', models.PositiveIntegerField()),
                ('cook_time_minutes', models.PositiveIntegerField()),
                ('ingredients', models.JSONField()),
                ('instructions', models.TextField()),
                ('emoji', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('food_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_recipes', to='foodbanks.foodbank')),
            ],
        ),
    ]
