# Generated by Django 5.2.11 on 2026-03-05 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('foodbanks', '0003_generatedrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBankSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pepesto_enabled', models.BooleanField(default=False)),
                ('accept_direct_delivery', models.BooleanField(default=True)),
                ('allow_donor_collection', models.BooleanField(default=False)),
                ('delivery_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='foodbanks.foodbank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('qr_poster', 'QR Poster'), ('qr_sticker', 'QR Sticker'), ('qr_social', 'QR Social')], max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('converted_to_donation', models.BooleanField(default=False)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='donations.donation')),
                ('food_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='foodbanks.foodbank')),
            ],
        ),
        migrations.CreateModel(
            name='FoodBankSupermarketPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supermarket', models.CharField(choices=[('tesco', 'Tesco'), ('sainsburys', 'Sainsburys'), ('asda', 'Asda'), ('waitrose', 'Waitrose')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('delivery_time_days', models.PositiveIntegerField(default=1)),
                ('food_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supermarket_preferences', to='foodbanks.foodbank')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('food_bank', 'supermarket'), name='unique_food_bank_supermarket')],
            },
        ),
    ]
