# Generated by Django 5.2.12 on 2026-03-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbanks', '0004_foodbanksettings_qrscan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedrecipe',
            name='dietary_restrictions',
            field=models.JSONField(default=list),
        ),
    ]
