# Generated by Django 5.2.11 on 2026-03-05 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodbanks', '0003_generatedrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donation_type', models.CharField(choices=[('recipe_kit', 'Recipe Kit'), ('individual_items', 'Individual Items')], max_length=20)),
                ('items', models.JSONField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('postcode', models.CharField(max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('food_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='foodbanks.foodbank')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='foodbanks.generatedrecipe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supermarket', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('received', 'Received')], max_length=20)),
                ('tracking_number', models.TextField(blank=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('received_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tracking', to='donations.donation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
